In [2]:
import numpy as np
import pandas as pd
import scipy
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import math
import time
from tqdm import tnrange, tqdm_notebook

## Alfa[0] = alfa0 
## Alfa[1] = alfa1
## Alfa[2] = alfa2
## Alfa[3] = alfa3
## Alfa[4] = alfa

In [3]:
def get_J(Alfa):
    J = np.zeros((5,5),float)
    J[0][0] = -Alfa[1]*Alfa[4]/Alfa[0]/Alfa[0]
    J[0][1] = Alfa[4]/Alfa[0]
    J[0][2] = 0
    J[0][3] = 0
    J[0][4] = Alfa[1]/Alfa[0]
    
    J[1][0] = 0
    J[1][1] = -Alfa[2]*Alfa[4]/Alfa[1]/Alfa[1]
    J[1][2] = Alfa[4]/Alfa[1]
    J[1][3] = 0
    J[1][4] = Alfa[2]/Alfa[1]

    J[2][0] = 0
    J[2][1] = 0
    J[2][2] = -Alfa[3]*Alfa[4]/Alfa[2]/Alfa[2]
    J[2][3] = Alfa[4]/Alfa[2]
    J[2][4] = Alfa[3]/Alfa[2]
    
    J[3][0] = 1
    J[3][1] = 1
    J[3][2] = 1
    J[3][3] = 1
    J[3][4] = 0
    
    J[4][0] = 0
    J[4][1] = 1
    J[4][2] = 2
    J[4][3] = 3
    J[4][4] = -1
    return J
def Saha(A,n,T,I):
    return A/n*T**(1.5)*math.exp(-I/T)
def get_F(A,n,T,Alfa,I1,I2,I3):
    return np.array([
        Alfa[1]*Alfa[4]/Alfa[0]-Saha(A,n,T,I1),
        Alfa[2]*Alfa[4]/Alfa[1]-Saha(A,n,T,I2),
        Alfa[3]*Alfa[4]/Alfa[2]-Saha(A,n,T,I3),
        Alfa[0]+Alfa[1]+Alfa[2]+Alfa[3]-1,
        Alfa[1]+2*Alfa[2]+3*Alfa[3]-Alfa[4],
    ])

In [4]:
n = 10**(20)
T = 3
I1 = 5.98
I2 = 18.83
I3 = 28.4
A = 6.06*10**(21)
Alfa = np.full(5,0.1,float)
dAlfa = np.full(5,1.0,float)
F = np.zeros(5,float)

#Начальное приближение
k1 = 0.4
k2 = 0.4
k3 = 0.3

Alfa[1]= k1
Alfa[2]= k1*k2
Alfa[3]= k1*k2*k3

Alfa[0]= 1 -Alfa[1]-Alfa[2]-Alfa[3]
Alfa[4]= Alfa[1]+2*Alfa[2]+3*Alfa[3]
if Alfa[0] < 0 or Alfa[4] < 0:
    print("Try Again!")

In [5]:

Epsilon = 10**(-8)
count = 0
count_max = 1000
Residual = []
while (np.linalg.norm(dAlfa) > Epsilon) and (count < count_max):
    print("Iteration №",count)
    J = get_J(Alfa)
    #print("Jacobi =",J)
    F = get_F(A,n,T,Alfa,I1,I2,I3)
    #print("F =",F)
    dAlfa = np.linalg.solve(J, -F)
    print(dAlfa)
    Residual.append(np.linalg.norm(get_F(A,n,T,Alfa,I1,I2,I3)))
    #Residual = get_F(A,n,T,Alfa+dAlfa,I1,I2,I3) - get_F(A,n,T,Alfa,I1,I2,I3)
    Alfa = Alfa + dAlfa
    print("Alfa =",Alfa)
    count = count + 1

Iteration № 0
[-7.9373219   6.87500892  1.2281292  -0.16581621  8.83381868]
Alfa = [-7.5453219   7.27500892  1.3881292  -0.11781621  9.69781868]
Iteration № 1
[ 52.28302494 -49.4860364   -2.45317454  -0.34381401 -55.4238275 ]
Alfa = [ 44.73770304 -42.21102748  -1.06504535  -0.46163022 -45.72600882]
Iteration № 2
[ 0.56292795 -3.09139076  1.46282412  1.0656387   3.03117356]
Alfa = [ 45.30063099 -45.30241824   0.39777877   0.60400848 -42.69483527]
Iteration № 3
[-0.06082559  0.09623907  0.22719408 -0.26260756 -0.23719545]
Alfa = [ 45.2398054  -45.20617917   0.62497285   0.34140092 -42.93203071]
Iteration № 4
[-0.37210707  0.74319328 -0.01715369 -0.35393253 -0.35291168]
Alfa = [ 4.48676983e+01 -4.44629859e+01  6.07819156e-01 -1.25316047e-02
 -4.32849424e+01]
Iteration № 5
[ 0.01825071 -0.0311128   0.00068885  0.01217325  0.00678463]
Alfa = [ 4.48859490e+01 -4.44940987e+01  6.08508004e-01 -3.58359317e-04
 -4.32781578e+01]
Iteration № 6
[ 2.31234709e-05 -3.97468249e-05  8.99024870e-07  1.57

In [6]:
Alfa[0]

44.885972167550335

In [7]:
Alfa[1]

-44.4941384356614

In [8]:
Alfa[2]

0.608508903072144

In [9]:
Alfa[3]

-0.00034263496108471477

In [10]:
Alfa[4]

-43.278148534400366